In [7]:
pip install mlxtend

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mlxtend in c:\users\user\appdata\roaming\python\python313\site-packages (0.23.4)
Requirement already satisfied: scipy>=1.2.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from mlxtend) (1.15.2)
Requirement already satisfied: numpy>=1.16.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from mlxtend) (2.2.3)
Requirement already satisfied: pandas>=0.24.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from mlxtend) (2.2.3)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in c:\users\user\appdata\roaming\python\python313\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas>=0.24.2->mlxtend) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\appdata\roaming\python\python313\site-packages (from pandas>=0.24.2->mlxtend) (2025.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [16]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [31]:
dataset = [
    ['book_1', 'book_2', 'book_3'],
    ['book_1', 'book_4'],
    ['book_2', 'book_3', 'book_4'],
    ['book_3', 'book_4', 'book_5'],
    ['book_1', 'book_3'],
    ['book_2', 'book_3', 'book_5'],
    ['book_1', 'book_5'],
    ['book_2', 'book_3', 'book_4'],
    ['book_3', 'book_4', 'book_5'],
    ['book_1', 'book_3'],
    ['book_2', 'book_3', 'book_4'],
    ['book_3', 'book_4', 'book_5'],
    ['book_1', 'book_3'],
    ['book_2', 'book_4', 'book_5']
]

In [32]:
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

    book_1  book_2  book_3  book_4  book_5
0     True    True    True   False   False
1     True   False   False    True   False
2    False    True    True    True   False
3    False   False    True    True    True
4     True   False    True   False   False
5    False    True    True   False    True
6     True   False   False   False    True
7    False    True    True    True   False
8    False   False    True    True    True
9     True   False    True   False   False
10   False    True    True    True   False
11   False   False    True    True    True
12    True   False    True   False   False
13   False    True   False    True    True

In [33]:
from mlxtend.frequent_patterns import fpgrowth

fpgrowth(df, min_support=0.6)

    support itemsets
0  0.785714      (2)

In [37]:

frequent_itemsets = apriori(df, min_support=0.4, use_colnames=True)
frequent_itemsets

    support          itemsets
0  0.428571          (book_1)
1  0.428571          (book_2)
2  0.785714          (book_3)
3  0.571429          (book_4)
4  0.428571          (book_5)
5  0.428571  (book_4, book_3)

In [36]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(book_4),(book_3),0.571429,0.785714,0.428571,0.750000,0.954545,1.0,-0.020408,0.857143,-0.100000,0.461538,-0.166667,0.647727
1,(book_3),(book_4),0.785714,0.571429,0.428571,0.545455,0.954545,1.0,-0.020408,0.942857,-0.181818,0.461538,-0.060606,0.647727